### PR TITLE
Use `gcovr` to enforce code coverage everywhere

### LINKED ISSUE #434: CI fails on `codecov` upload for PRs from forks
### Bug description

**Platform (please complete the following information):**
 - OS: Ubuntu Jammy
 - `Beluga` version: https://github.com/Ekumen-OS/beluga/commit/5493d4b4055dbbfd138660e98b7e98bad7119d0c

### How to reproduce
1. Fork https://github.com/Ekumen-OS/beluga
2. Branch off `main` and make a modification
3. Pull request your branch back

**Expected behavior**
CI passes once `beluga` builds and all linters, static analyzers, and tests are satisfied.

**Actual behavior**
CI fails to upload coverage reports to `codecov`. See https://github.com/Ekumen-OS/beluga/actions/runs/11044455813/job/30706358854?pr=431 for an instance of this.

### Additional context

This seems to be [expected](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow). We need a `codecov` alternative for PRs that are not local to this repo.

### PR DESCRIPTION
**Pull request by hidmic**
### Proposed changes

Closes #434 (kinda). This patch introduces `gcovr` for code coverage enforcement for all distributions and workflows. `codecov` remains in use for Humble jobs triggered by local workflows.

#### Type of change

- [x] 🐛 Bugfix (change which fixes an issue)
- [ ] 🚀 Feature (change which adds functionality)
- [ ] 📚 Documentation (change which fixes or extends documentation)

### Checklist

- [x] Lint and unit tests (if any) pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

## Additional comments

The choice of `gcovr` in addition to `lcov` has to do with feature support. Only  the newest versions of `lcov`, available starting Noble, have the "fail under X coverage" feature. Alas, `colcon`'s `lcov` integration is all broken in Noble -.-.

### CODE REVIEW

File: tools/check-code-coverage.sh [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+# Enforce code coverage limits
+
+[[ -z "${WITHIN_DEV}" ]] && echo -e "\033[1;33mWARNING: Try running this script inside the development container if you experience any issues.\033[0m"
+
+set -o errexit
+
+gcovr --fail-under-line 95 -j -u -f 'src/beluga/.*' -e '.*/test/.*cpp' build/
+# NOTE: Enable Python code coverage checks when attained
+# (cd coveragepy && python3 -m coverage report --fail-under=95)
```
Comment (hidmic) [inline tools/check-code-coverage.sh:25]: Note we cannot enforce anything for Python code yet. We are not doing great in that department, though it's all tools and support code.

**Comment by hidmic** [comment]
Noetic is below 95%. Rolling is just failing everywhere.

**Review by nahueespinosa — APPROVED** [review]
LGTM
