### PR TITLE
Fix to likelihood map pre-calculation performance for large maps

### LINKED ISSUE #472: When there are no obstacles in the map, make_likelihood_field() turns the map into one large block of obstacles
### Bug description

If there are no obstacles in the map, the `make_likelihood_field()` function in the Likelihood turns the likelihood map into a solid block of obstacles where all pixels are at distance 0 from an obstacle.

Instead of that, all cells should be assigned the minimum possible likelihood value, corresponding to the `laser_likelihood_max_dist` parameter.

We did not really pay attention to this limit case, and cristalized this bug into [a unit test that checks just this](https://github.com/Ekumen-OS/beluga/blob/main/beluga/test/beluga/algorithm/test_distance_map.cpp#L51-L55).

Later it also became part of [this other unit test](https://github.com/Ekumen-OS/beluga/blob/main/beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp#L304-L307), which also checks a totally unexpected value given that there no obstacles in the map.

**Platform (please complete the following information):**
 - OS: [e.g. Ubuntu Focal]
 - `Beluga` version: [e.g. tag, commit sha]

### How to reproduce

Check that the unit tests listed above currently pass in the code, despite the values being checked being incorrect.

**Expected behavior**

If there are no obstacles in the map, all cells should be assigned the minimum possible likelihood value, corresponding to the `laser_likelihood_max_dist` parameter.

**Actual behavior**

They are not.

### Additional context

Discovered while fixing #469

### PR DESCRIPTION
**Pull request by glpuga**
### Proposed changes

Addresses #468 
Also fixes #472 

#### Type of change

- [x] 🐛 Bugfix (change which fixes an issue)
- [ ] 🚀 Feature (change which adds functionality)
- [ ] 📚 Documentation (change which fixes or extends documentation)

### Checklist

_Put an `x` in the boxes that apply. This is simply a reminder of what we will require before merging your code._

- [x] Lint and unit tests (if any) pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

### Additional comments

_Anything worth mentioning to the reviewers._

### CODE REVIEW

File: beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp [hunk 1]
```diff
@@ -276,7 +276,7 @@ TEST(LikelihoodFieldModelUnknownSpace, GridWithRotationAndOffset) {
   }
 }
 
-TEST(LikelihoodFieldModelUnknownSpace, GridUpdates) {
+TEST(LikelihoodFieldModelUnknownSpace, DISABLED_GridUpdates) {
```
Comment (glpuga) [inline beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp:279]: I still need to figure why this test fails now.

File: beluga/include/beluga/algorithm/distance_map.hpp [hunk 2]
```diff
@@ -54,19 +55,22 @@ template <class Range, class DistanceFunction, class NeighborsFunction>
...
+    std::invoke_result_t<DistanceFunction, std::size_t, std::size_t> max_distance_value) {
   struct IndexPair {
     std::size_t nearest_obstacle_index;
     std::size_t index;
   };
 
   using DistanceType = std::invoke_result_t<DistanceFunction, std::size_t, std::size_t>;
-  auto distance_map = std::vector<DistanceType>(ranges::size(obstacle_mask));
+
+  auto distance_map = std::vector<DistanceType>(ranges::size(obstacle_mask), max_distance_value);
```
Comment (glpuga) [inline beluga/include/beluga/algorithm/distance_map.hpp:67]:
```suggestion
  auto distance_map = std::vector<DistanceType>(ranges::size(obstacle_mask), max_distance_value);
```

File: beluga/include/beluga/algorithm/distance_map.hpp [hunk 3]
```diff
@@ -54,19 +55,21 @@ template <class Range, class DistanceFunction, class NeighborsFunction>
...
 
   using DistanceType = std::invoke_result_t<DistanceFunction, std::size_t, std::size_t>;
-  auto distance_map = std::vector<DistanceType>(ranges::size(obstacle_mask));
+  auto distance_map = std::vector<DistanceType>(ranges::size(obstacle_mask), max_distance_value);
   auto visited = std::vector<bool>(ranges::size(obstacle_mask), false);
 
   auto compare = [&distance_map](const IndexPair& first, const IndexPair& second) {
     return distance_map[first.index] > distance_map[second.index];
   };
+
```
Comment (glpuga) [inline beluga/include/beluga/algorithm/distance_map.hpp:72]:
```suggestion
```

File: beluga/include/beluga/algorithm/distance_map.hpp [hunk 4]
```diff
@@ -15,6 +15,7 @@
 #ifndef BELUGA_ALGORITHM_DISTANCE_MAP_HPP
 #define BELUGA_ALGORITHM_DISTANCE_MAP_HPP
 
+#include <algorithm>
```
Comment (glpuga) [inline beluga/include/beluga/algorithm/distance_map.hpp:18]:
```suggestion
```

File: beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp (hunk 1 above)
Comment (glpuga) [reply beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp]: Fixed. The reason the test began to fail was because the behavior tested was actaully wrong. See #472 .

File: beluga/include/beluga/sensor/data/value_grid.hpp [hunk 5]
```diff
@@ -15,6 +15,7 @@
 #ifndef BELUGA_SENSOR_DATA_VALUE_GRID_HPP
 #define BELUGA_SENSOR_DATA_VALUE_GRID_HPP
 
+#include <cmath>
```
Comment (glpuga) [inline beluga/include/beluga/sensor/data/value_grid.hpp:18]:
```suggestion
```

File: beluga/include/beluga/sensor/likelihood_field_model.hpp [hunk 6]
```diff
@@ -180,19 +175,22 @@ class LikelihoodFieldModel {
...
     // to minimize memory usage when dealing with large maps
-    auto distance_map = nearest_obstacle_distance_map(grid.obstacle_mask(), squared_distance, neighborhood);
+    auto distance_map = nearest_obstacle_distance_map(
+        grid.obstacle_mask(), squared_distance, neighborhood, static_cast<float>(squared_max_distance));
 
     if (params.model_unknown_space) {
-      const double inverse_max_distance = 1 / params.max_laser_distance;
-      const double background_distance = -two_squared_sigma * std::log((inverse_max_distance - offset) / amplitude);
+      const auto inverse_max_distance = 1 / params.max_laser_distance;
+      const auto background_distance = -two_squared_sigma * std::log((inverse_max_distance - offset) / amplitude);
```
Comment (glpuga) [inline beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: @hidmic @DPR00 this should be a squared distance, is it?

Comment (DPR00) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: I don't think so. The background distance is that function according to the formula. However, I think in the next line should be like this:
```
distance_map |= beluga::actions::overlay(
          grid.unknown_mask(), std::min(params.max_obstacle_distance, static_cast<float>(background_distance)));
```
The overlay action will write the distance value into the distance_map, so none of the values shouldn't be squared. Sorry, I missed this.

Comment (glpuga) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: Nop. The somewhat misnamed distance_map does not store linear distances, stored distances squared to avoid calculating the square root only to raise to the square again. The to_likehood() function expects distances to be actually squared distances, that's why this `background_distance` should actually be a distance squared too.

Comment (DPR00) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: Then, you're right it should be squared.

Comment (glpuga) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: Now, I see that the dimensionality in `background_distance` is given by `two_squared_sigma`, which by the name seems to be a distance squared, so maybe only the name `background_distance` is wrong, and not the value.

My question is, according to the model you guys followed here, is the value calculated there a squared distance?

Comment (DPR00) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: So, the background distance is obtained by clearing `dist` from the equation on line 8:
image
Therefore, the implemented formula here indeed corresponds to a squared distance. Likewise, the name `background_distance` is wrong. It should be something like `squared_background_distance`.

Comment (glpuga) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:187]: Awesome, I can correct that. Thanks @DPR00 !

Comment (DPR00) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp]: thanks for noticing that!

File: beluga/include/beluga/algorithm/distance_map.hpp [hunk 7]
```diff
@@ -48,20 +48,22 @@ namespace beluga {
...
+ * \param max_distance_value The maximum distance anywhere in the map. Values over this will be truncated to this value.
  * \return A map where each cell value is the distance to the nearest object.
  */
 template <class Range, class DistanceFunction, class NeighborsFunction>
 auto nearest_obstacle_distance_map(
     Range&& obstacle_mask,
     DistanceFunction&& distance_function,
-    NeighborsFunction&& neighbors_function) {
+    NeighborsFunction&& neighbors_function,
+    std::invoke_result_t<DistanceFunction, std::size_t, std::size_t> max_distance_value) {
```
Comment (hidmic) [inline beluga/include/beluga/algorithm/distance_map.hpp:59]: @glpuga nit^2: consider making `DistanceType` below a template parameter with default, then use it here.

File: beluga/include/beluga/sensor/likelihood_field_model.hpp [hunk 8]
```diff
@@ -180,19 +175,23 @@ class LikelihoodFieldModel {
 
     const auto neighborhood = [&grid](std::size_t index) { return grid.neighborhood4(index); };
 
+    const auto squared_max_distance = static_cast<float>(params.max_obstacle_distance * params.max_obstacle_distance);
+
     // determine distances to obstacles and calculate likelihood values in-place
     // to minimize memory usage when dealing with large maps
-    auto distance_map = nearest_obstacle_distance_map(grid.obstacle_mask(), squared_distance, neighborhood);
+    auto distance_map = nearest_obstacle_distance_map(
+        grid.obstacle_mask(), squared_distance, neighborhood, static_cast<float>(squared_max_distance));
```
Comment (hidmic) [inline beluga/include/beluga/sensor/likelihood_field_model.hpp:183]: @glpuga I think we can spare this `static_cast`, we already cast it to `float` above.

File: beluga/test/beluga/algorithm/test_distance_map.cpp [hunk 9]
```diff
@@ -44,38 +44,44 @@ auto make_neighbors_function(std::size_t size) {
...
 }
 
 TEST(DistanceMap, Case3) {
   auto map = std::array<bool, 6>{false, false, false, false, false, true};
-  auto distance_map = beluga::nearest_obstacle_distance_map(map, array_distance, make_neighbors_function(6));
+  auto distance_map = beluga::nearest_obstacle_distance_map(map, array_distance, make_neighbors_function(6), 10);
   ASSERT_THAT(distance_map, testing::ElementsAre(5, 4, 3, 2, 1, 0));
 }
 
+TEST(DistanceMap, MinDistaceSet) {
```
Comment (hidmic) [inline beluga/test/beluga/algorithm/test_distance_map.cpp:81]: @glpuga nit: 
```suggestion
TEST(DistanceMap, MinDistanceSet) {
```

**Review by hidmic — APPROVED** [review]
Awesome!

File: beluga/test/beluga/algorithm/test_distance_map.cpp (hunk 9 above)
Comment (glpuga) [reply beluga/test/beluga/algorithm/test_distance_map.cpp:81]: Fixed.

File: beluga/include/beluga/sensor/likelihood_field_model.hpp (hunk 8 above)
Comment (glpuga) [reply beluga/include/beluga/sensor/likelihood_field_model.hpp:183]: True, fixed.

File: beluga/include/beluga/algorithm/distance_map.hpp (hunk 7 above)
Comment (glpuga) [reply beluga/include/beluga/algorithm/distance_map.hpp:59]: I could not get it to build. If you can provide a version of this that builds, I'll happily take it.

Comment (hidmic) [reply beluga/include/beluga/algorithm/distance_map.hpp:59]: Hmm, it's inferring the template parameter from a literal and breaking down. Nevermind.
